import {
  Box,
  Button,
  Dialog,
  DialogActions,
  DialogContent,
  DialogTitle,
  Stack,
  TextField,
  Typography,
} from "@mui/material";
import { useEffect, useState } from "react";
import type { ApiContentSummary } from "../lib/eaix-api";

interface DocumentSummaryModalProps {
  open: boolean;
  onClose: () => void;
  summary: ApiContentSummary | null;
  actor: string;
  actorCanFinalize: boolean;
  onFinalize: (summary: string) => Promise<void>;
}

export function DocumentSummaryModal({
  open,
  onClose,
  summary,
  actor,
  actorCanFinalize,
  onFinalize,
}: DocumentSummaryModalProps) {
  const [editingSummary, setEditingSummary] = useState("");
  const [saving, setSaving] = useState(false);

  useEffect(() => {
    if (summary) {
      setEditingSummary(
        summary.status === "APPROVED"
          ? summary.summaryFinal
          : summary.summaryDraft,
      );
    }
  }, [summary]);

  if (!summary) {
    return null;
  }

  const canFinalize =
    actorCanFinalize &&
    summary.uploadedBy === actor &&
    summary.status !== "APPROVED";

  const handleFinalize = async () => {
    if (!canFinalize) {
      return;
    }

    const normalized = editingSummary.trim();
    if (!normalized) {
      return;
    }

    setSaving(true);
    try {
      await onFinalize(normalized);
    } finally {
      setSaving(false);
    }
  };

  return (
    <Dialog
      open={open}
      onClose={onClose}
      maxWidth="md"
      fullWidth
      PaperProps={{
        sx: {
          background: "linear-gradient(135deg, #16525c 0%, #0b161f 100%)",
          border: "1px solid rgba(22,200,200,0.3)",
          borderRadius: 2,
        },
      }}
    >
      <DialogTitle sx={{ color: "#16c6b0" }}>
        Summary: {summary.title}
      </DialogTitle>
      <DialogContent sx={{ background: "#0d1b26" }}>
        <Stack spacing={1.5}>
          <Typography sx={{ color: "rgba(205,220,229,0.9)" }}>
            Generated by {summary.summaryAgent}. Owner can finalize this summary
            for all users.
          </Typography>
          <Typography
            sx={{ color: "rgba(166,195,205,0.8)", fontSize: "0.85rem" }}
          >
            Status: {summary.status}
            {summary.summaryApprovedBy
              ? ` • Approved by ${summary.summaryApprovedBy}`
              : " • Awaiting owner approval"}
          </Typography>
          <TextField
            multiline
            minRows={6}
            fullWidth
            value={editingSummary}
            disabled={!canFinalize || saving}
            onChange={(event) => setEditingSummary(event.target.value)}
            placeholder="Summary content"
            sx={{
              "& .MuiOutlinedInput-root": {
                color: "rgba(205,220,229,0.95)",
                "& fieldset": { borderColor: "rgba(22,200,200,0.28)" },
                "&:hover fieldset": { borderColor: "rgba(22,200,200,0.5)" },
                "&.Mui-focused fieldset": { borderColor: "#16c6b0" },
              },
            }}
          />
          {summary.status === "APPROVED" && (
            <Box>
              <Typography
                sx={{ color: "rgba(166,195,205,0.8)", fontSize: "0.84rem" }}
              >
                This approved summary is visible to all users.
              </Typography>
            </Box>
          )}
        </Stack>
      </DialogContent>
      <DialogActions>
        <Button onClick={onClose} sx={{ color: "rgba(166,195,205,0.9)" }}>
          Close
        </Button>
        {canFinalize && (
          <Button
            variant="contained"
            onClick={handleFinalize}
            disabled={saving || !editingSummary.trim()}
            sx={{
              background: "linear-gradient(135deg, #16c6b0 0%, #0fa89b 100%)",
              color: "#0b161f",
              fontWeight: 700,
            }}
          >
            {saving ? "Finalizing..." : "Finalize Summary"}
          </Button>
        )}
      </DialogActions>
    </Dialog>
  );
}
